### ISSUE TITLE
colorize=true the file output confused.

### ISSUE THREAD

**Issue by balzaron** [Delgan/loguru#26] opened 2018-12-27 06:12 UTC
^[[32m2018-12-27 14:04:17.103^[[0m | ^[[1mINFO    ^[[0m | ^[[36m__main__^[[0m:^[[36m<module>^[[0m:^[[36m9^[[0m - ^[[1mb'in8'^[[0m

but actually the output should be
2018-12-27 14:07:20.106 | INFO     | __main__:<module>:9 - b'in8'

and my config is as below:

from loguru import logger

__logInfo= dict(
    rotation='1KB',
    enqueue=True,
    # colorize=True,
    # format="<green>{time}</green> <level>{message}</level>",
    encoding='utf-8',
)
fp='name_{time}.log'
logger.add(fp,**__logInfo)

**Comment by Delgan** [comment] 2018-12-28 00:18
Hello @balzaron.

Sadly, I cannot reproduce your problem.

I can think of two reasons why you would see colors ansi codes in your file:
* The `colorize=True` is actually not commented in your code (maybe a confusion between `_logInfo` and `__logInfo`?)
* The environmet variable `LOGURU_COLORIZE` is set to `True`

Otherwise, if `colorize=None`, it should be automatically detected, and as your sink is a simple `str` representing a file, Loguru will strip the ansi codes.

**Comment by Delgan** [comment] 2019-01-20 19:44
@balzaron Did you manage to reproduce the error?

I d'ont think there is a problem with Loguru. It depens on your configuration. If you `.add()` a file-sink, make sure `colorize=False` (or `None` the default). Otherwise, it will add the weird `^[[32m` characters that you saw (they are used by the terminal to color the output, but a file can't contain colors).

**Comment by Delgan** [comment] 2019-03-03 21:58
I'm closing this as it seems more to be a configuration problem.

**Closed by Delgan** 2019-03-03 21:58 UTC

**Comment by philipobrien** [comment] 2019-06-12 09:28
Commenting here as I'm seeing a similar problem even when setting `colorize=False`. I'm using `loguru` and `graypy` to forward my logs to `graylog`

```
from loguru import logger
import graypy
handler = graypy.GELFUDPHandler('graylog', 12201)
logger.add(handler, colorize=False)
```

but the logs are still appearing in graylog with the color codes

> AssertionError: [38;5;81massert[39m[38;5;15m [39m[38;5;15mRoute[39m[38;5;197m.[39m[38;5;15mquery[39m[38;5;197m.[39m[38;5;15mfilter_by[39m[38;5;15m([39m[38;5;15mpatient_id[39m[38;5;197m=[39m[38;5;15mpatient[39m[38;5;197m.[39m[38;5;15mid[39m[38;5;15m)[39m[38;5;197m.[39m[38;5;15mall[39m[38;5;15m([39m[38;5;15m)[39m

**Comment by Delgan** [comment] 2019-06-12 18:41
Hi @philipobrien.

I see `AssertionError` in your example: do the color codes appear in ll the logs, or just in the exceptions?
Could you try to run `pip uninstall loguru` and then `pip install git+https://github.com/delgan/loguru@master` please? As many modifications has been made since `v0.2.5`, I would like to know if this bug has been fixed.

**Comment by philipobrien** [comment] 2019-06-13 09:24
The code in question is running in a docker container, with dependencies installed using pipenv. So installing loguru with `pipenv install -e git+https://github.com/delgan/loguru.git@master#egg=loguru` works but for some reason in the container trying to import loguru results in `ModuleNotFoundError: No module named 'loguru'`. I might not have the time to debug this but if I do I'll post an update here

**Comment by philipobrien** [comment] 2019-06-13 09:42
I can, however, confirm that with v0.2.5 the colour codes to appear in the logs, so if I create a handler with `logger.add("output.log", colorize=False)` and then call `logger.exception("no routes exist")`, in `output.log` I see 

```
AssertionError: [38;5;81massert[39m[38;5;15m [39m[38;5;15mRoute[39m[38;5;197m.[39m[38;5;15mquery[39m[38;5;197m.[39m[38;5;15mfilter_by[39m[38;5;15m([39m[38;5;15mpatient_id[39m[38;5;197m=[39m[38;5;15mpatient[39m[38;5;197m.[39m[38;5;15mid[39m[38;5;15m)[39m[38;5;197m.[39m[38;5;15mall[39m[38;5;15m([39m[38;5;15m)[39m
```

**Comment by Delgan** [comment] 2019-06-13 18:15
Thank you for taking the time to test this, @philipobrien!

It's still unclear to me: do you see the symbol `"�[38;5;81"`` around logged messages like `"no routes exists"` or only around the exception message as in your example?

Also, could you please tell me if you're using Linux or Windows (or Mac)?

**Comment by philipobrien** [comment] 2019-06-14 08:45
I discovered the culprit. In my docker compose file, under the corresponding service definition I had

```
stdin_open: true
tty: true
```

Removing these and the `AssertionError` gets logged as 

```
AssertionError: assert Route.query.filter_by(patient_id=patient.id).all()
```

Adding those two lines back in and the `AssertionError` gets logged with the symbols e.g.

```
AssertionError: [38;5;81massert[39m[38;5;15m [39m[38;5;15mRoute[39m[38;5;197m.[39m[38;5;15mquery[39m[38;5;197m.[39m[38;5;15mfilter_by[39m[38;5;15m([39m[38;5;15mpatient_id[39m[38;5;197m=[39m[38;5;15mpatient[39m[38;5;197m.[39m[38;5;15mid[39m[38;5;15m)[39m[38;5;197m.[39m[38;5;15mall[39m[38;5;15m([39m[38;5;15m)[39m
```

This makes sense for me from the point of view of logging to the terminal, but I didn't expect it to also affect the logs being written directly to a log file.

**Comment by Delgan** [comment] 2019-06-14 09:24
@philipobrien Well, that's weird indeed. File handlers should not contain color codes except if `open("some_file.txt").isatty()` returns `True` on your docker container for some reason, maybe related to the `tty` parameter as you discovered it.

However, the fact that you saw color codes even if `colorize=False` is surprising. It definitely looks like a bug, hopefully it should be fixed in `v0.3.0` as the exception coloration process has been entirely refactored.

**Comment by philipobrien** [comment] 2019-06-14 10:05
So I just reran it with 

```
stdin_open: true
tty: true
```

and ssh'ed to the container, and confirmed that `open("output.log").isatty()` returns `False`, and yet the colour codes are showing in the file.

**Comment by Delgan** [comment] 2019-06-14 10:13
@philipobrien I think this is due to an old bug in `better_exception_fork` (which is used by `loguru`). Thanks for having tested that again. ;)

**Comment by philipobrien** [comment] 2019-06-14 10:19
No worries. Thanks for the prompt responses (and excellent library)!
