### ISSUE TITLE
What's the best way to use Loguru in a library?

### ISSUE THREAD

**Issue by araichev** [Delgan/loguru#349] opened 2020-10-12 00:00 UTC
Hiya, i'm making a Python library and would like to use Loguru instead of the standard logging library.
I can find advice on the latter approach, e.g. [here](https://docs.python-guide.org/writing/logging/#logging-in-a-library), but how should i proceed with the former approach?

**Comment by Delgan** [comment] 2020-10-12 18:02
Hi!

If you plan to use `loguru` in a library, the main rule is to call `logger.disable("my_library")` and to not use `.add()` at all. The users of your library should be responsible of configuring the handlers themselves.

Thanks to [`.disable()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) they will not see any logs from your library except if they explicit ask for by using `logger.enable("my_library")`.

**Comment by araichev** [comment] 2020-10-12 20:35
Thanks, will do.
And should i make `loguru` a development dependency in the library ---i use Poetry for dependency management--- or a production dependency?
In the former case, the user's app will depend on `loguru`.

**Comment by Delgan** [comment] 2020-10-12 20:46
I guess you need to make it a production dependency, otherwise your users will get an `ImportError` when they try to use your library, right? Even if the `logger` output is disabled, the `from loguru import logger` and all `logger.info("...")` will still be present in your code.

**Comment by araichev** [comment] 2020-10-12 20:54
Righto.
Thanks for your quick and helpful response.

**Comment by trallnag** [comment] 2020-10-20 22:29
While this issue is open I'll let myself in to ask another question can be also summarized with "What's the best way to use Loguru in a library?", @Delgan:

Is there a best practice where to put the configuration code when using Loguru in a project that is not a library? Currently I just place it right next to the main function (or where ever else the init happens) for example like this:

```python
def configure_logging() -> None:
    logger.remove()

    if s.LOG_JSON:
        fmt = "{message}"
        logger.add(sys.stderr, format=fmt, serialize=True, level=s.LOG_LEVEL)
    else:
        fmt = "<green>{time:HH:mm:ss}</green> <level>{level}</level> <cyan>{function}</cyan> {message} <dim>{extra}</dim>"
        logger.add(sys.stderr, colorize=True, format=fmt, level=s.LOG_LEVEL)
```

But maybe something like `__init__.py` is more suitable?

**Comment by Delgan** [comment] 2020-10-21 06:41
Hi @trallnag. I guess it depends on one's preferences. I can't find any source providing authoritative answer on this issue. I think it makes sense to have this function close to where the logger is initialized. I have rarely seen functions declared in the `__init__.py`, do you see any benefit? 

In any case, I like to call `configure_logging()` inside a `if __name__ == "__main__"` block for two reasons:
* This allows some functions of my application to be imported and reused by other projects without touching the logger.
* This allows to configure the logger from command line arguments (like `--verbose`)

Although it may be a good idea to additionally import the `configure_logger` in a `__init__.py` in case one wants to use your application programmatically (like a library).

**Comment by trallnag** [comment] 2020-10-21 09:15
Thanks for the helpful answer, @Delgan. I considered putting the function into `__init__.py` (and calling it there) to ensure that the loguru is configured for the whole module. But your approach is more reasonable

**Comment by bee-san** [comment] 2021-02-15 13:41
Hey!

I have both a library and a CLI app, how best should I use Loguru?

**Comment by Delgan** [comment] 2021-02-15 21:15
Hey @bee-san.

If I'm referring to [this version of your file](https://github.com/HashPals/Name-That-Hash/blob/14af00b7a512d7a34394bf6d66a1c354c96af42d/name_that_hash/runner.py), you should not call `.add()` at the start of your module. Instead, you should call `logger.disable("name_that_hash")` (or maybe `logger.disable("runner")` depending on how is used your library). That way, the messages coming from your library will be purely ignored no matter what are the added handlers.

In `set_logger()` you should re-`enable()` the disabled module. You should also configure the required handlers. Then, call `set_logger()` inside your `main()` function when your module is used a a CLI.

It should work fine like that. :+1:

**Comment by Delgan** [comment] 2021-03-15 21:55
I'm closing this issue as the question has been answered.  +1

**Closed by Delgan** 2021-03-15 21:55 UTC
Labels: question

**Comment by eitel13** [comment] 2023-11-15 10:39
Maybe _slightly_ related so I will share what I did too 🙂 

We helped develop an internal and I wanted to make this package use Loguru 💪 

Of course though, project teams that might use this package, might want to use the default logging module (🤮) OR they might not want to have a combination of their standard logs mixed with the Loguru logs from the package.

So, instead of `logger.disable("package-name")`, in an `__init__.py` file we did this:

```Python
from loguru import logger

logger.remove()

class PropagateHandler(logging.Handler):
    def emit(self, record: logging.LogRecord) -> None:
        logging.getLogger(record.name).handle(record)

logger.add(PropagateHandler(), format="{message}")
```

In this way:

- We have Loguru being used in our package
- Anyone using the package can simply "disable" the Loguru logs but still [have the logs propagated into the logger](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) of their choice
- If they really don't want to see the logs from our package, they can go the `logger.disable("package-name")` route

@Delgan if you have a "better" approach, please do share! 🙇

**Comment by Delgan** [comment] 2023-11-18 09:46
Hi @eitel13.

Usually I don't advise to remove or add any handler during initialization of a library. This is because it could potentially interfere with the global logging configuration of other parts of the application, leading to unexpected behavior and making it harder for users to manage their logs cohesively.

Instead, I recommend creating and documenting a function that allows users to configure the logger. But this function should not, in theory, be called automatically.

That being said, your use case is interesting. I'm thinking of creating a `logger.bridge()` function to ease integration between `loguru` and standard `logging`. Maybe `logger.bridge(propagate=True)` will be possible solution for you in the future.

**Comment by eitel13** [comment] 2023-11-20 15:29
Hey @Delgan ! 

> Maybe `logger.bridge(propagate=True)` will be possible solution for you in the future.

That sounds amazing if you manage to incorporate it! 🚀 

In the meantime, thank you for your words of advice 💪
