### ISSUE TITLE
Suggested workaround for multiprocessing on windows

### ISSUE THREAD

**Issue by salihkilic** [Delgan/loguru#190] opened 2019-12-17 11:37 UTC
Hey there guys, after having troubles using this library on Windows I found the [example from the docs ](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)for using multiprocessing with Loguru  and got in a bit of experimental mood.   

The example describes how a lot of sinks are not pickable and thus cannot be used in multiprocessing but when we define a logging class that inherits from `multiprocessing.Process` we can instantiate the logger (or add sinks to it) by overriding the `Process.run()` function (which you have to anyway in this situation).   

Here is a simple example:

```python
from loguru import logger

import sys
import multiprocessing
import random
import time


class LogWorker(multiprocessing.Process):

    def __init__(self, mp_logger):
        super(LogWorker, self).__init__()
        self.file_logger = mp_logger

    def log_it(self):
        for x in range(2):
            msg = f"Worker: {multiprocessing.current_process().name} - Random number: {random.randint(0, 1000)}"
            self.file_logger.debug(msg)
            time.sleep(random.random())

    def run(self) -> None:
        # 2 When we add a sink here, it doesn't need to be pickled
        self.file_logger.add(sys.stderr)
        self.file_logger.debug(f"{multiprocessing.current_process().name} now has: {logger.__repr__()}")
        # 3 Now we can log to stderr *and* to logfile on windows.
        self.log_it()


if __name__ == '__main__':
    # 1 We remove the part that can't be pickled first
    logger.debug(f" __main__ logger now has: {logger.__repr__()}")
    logger.remove()
    logger.add("log_file.log", enqueue=True)
    logger.debug(f" __main__ logger now has: {logger.__repr__()}")

    workers = []
    for x in range(3):
        worker = LogWorker(logger)
        workers.append(worker)
        worker.start()
```

I believe one could even define a function outside of the multiprocessing class that does all the setup for the logger, returns it and attaches it to the class during the `Process.run()` function.  Logging while multiprocessing on Windows is really ass. After a lot of googling I found this library and this is the first time I've got a working solution that doesn't need a lot of boilerplate code and custom handlers and whatnot. So maybe this could be used as a working example for that section of the docs?

edit:
Whoops! Forgot the logging example results from above script:

`Terminal`:
```
2019-12-17 12:38:43.310 | DEBUG    | __main__:<module>:31 -  __main__ logger now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.443 | DEBUG    | __mp_main__:run:24 - LogWorker-1 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.443 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-1 - Random number: 59
2019-12-17 12:38:43.492 | DEBUG    | __mp_main__:run:24 - LogWorker-2 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.492 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-2 - Random number: 922
2019-12-17 12:38:43.539 | DEBUG    | __mp_main__:run:24 - LogWorker-3 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.539 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-3 - Random number: 241
2019-12-17 12:38:43.702 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-1 - Random number: 396
2019-12-17 12:38:43.832 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-3 - Random number: 949
2019-12-17 12:38:44.471 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-2 - Random number: 99
```

`Logfile`:
```
2019-12-17 12:38:43.317 | DEBUG    | __main__:<module>:34 -  __main__ logger now has: <loguru.logger handlers=[(id=1, level=10, sink='log_file.log')]>
2019-12-17 12:38:43.443 | DEBUG    | __mp_main__:run:24 - LogWorker-1 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.443 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-1 - Random number: 59
2019-12-17 12:38:43.492 | DEBUG    | __mp_main__:run:24 - LogWorker-2 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.492 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-2 - Random number: 922
2019-12-17 12:38:43.539 | DEBUG    | __mp_main__:run:24 - LogWorker-3 now has: <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>
2019-12-17 12:38:43.539 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-3 - Random number: 241
2019-12-17 12:38:43.702 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-1 - Random number: 396
2019-12-17 12:38:43.832 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-3 - Random number: 949
2019-12-17 12:38:44.471 | DEBUG    | __mp_main__:log_it:18 - Worker: LogWorker-2 - Random number: 99
```

**Comment by salihkilic** [comment] 2019-12-17 11:47
Now that I think about it. One could make a multiprocessing alternative class to `loguru.logger` like `loguru.mp_logger `this way I imagine? I have never forked or pulled a git project before, so if there's interest in me trying to work on a prototype I'm willing to find out how I can contribute. :)

**Comment by salihkilic** [comment] 2019-12-17 12:00
Sorry for the amount of comments after each other, but here is an even smaller example to show how clean it can be done without passing the logger to the worker at all :

```python
from loguru import logger

import multiprocessing
import random


class LogWorker(multiprocessing.Process):

    def __init__(self):
        super(LogWorker, self).__init__()
        self.file_logger = None

    def log_it(self):
        for x in range(2):
            msg = f"Worker: {multiprocessing.current_process().name} - Random number: {random.randint(0, 1000)}"
            self.file_logger.debug(msg)

    def run(self) -> None:
        self.file_logger = logger
        self.file_logger.add("log_file.log", enqueue=True)
        self.log_it()


if __name__ == '__main__':

    workers = []
    for x in range(3):
        worker = LogWorker()
        workers.append(worker)
        worker.start()
```

**Comment by Delgan** [comment] 2019-12-19 21:40
Hey @salihkilic, I realy appreciate your "experimental mood" and suggestions, thanks! :smile: 

So, basically, you propose to call `logger.add(sys.stderr)` inside each started sub-process worker. That could work, but, this means that every sub-process will use a different sink without any synchronization between each others.

This will lead to unexpected behavior as the one described in #108: multiple processes will try to write on `sys.stderr` at the same time which will cause possible conflicts. That's why if the sink is the same, it **needs** to be added with `enqueue=True` and the `logger` has to be inherited by the sub-process.

**Comment by salihkilic** [comment] 2019-12-21 16:50
This is where my knowledge on multiprocessing and this library falls a bit short. If loguru's `logger` is loaded after instantiation (ie. in `run()` ), is it the same object (in memory)? I believe that one of the reasons it can't be passed during instantiation is because loguru's `logger` uses a `threading`-based queue for synchronization, which can't be pickled into a newly spawned process, right? 

But on the other hand, if I make my custom multi-processing logger wrapper this way and I synchronize the `logger`'s `sys.stderr` output within the worker (with a multiprocessing-lock or some other signal/lock) I imagine it would work.

So I guess this is not a fool-proof solution but the docs gave me the idea it's simply not possible. That's why I thought writing a little example wrapper that at least gives the user _some_ options (including your caveat) might be interesting to include into that section of the docs.

**Comment by salihkilic** [comment] 2019-12-21 17:24
I wrote a little example wrapper for what I'm talking about:

```
from loguru import logger

import multiprocessing
import uuid


class MultiProcessLogger(multiprocessing.Process):

    def __init__(self, lock, sync_confirm):
        super(MultiProcessLogger, self).__init__()
        self.mp_logger = None
        self.mp_lock = lock
        self.sync_confirm = sync_confirm

    def debug(self):
        with self.mp_lock:
            msg = f"Worker: {multiprocessing.current_process().name} " \
                  f"- Sync Confirm: {self.sync_confirm}"
            self.mp_logger.debug(msg)

    def info(self):
        with self.mp_lock:
            msg = f"Worker: {multiprocessing.current_process().name} " \
                  f"- Sync Confirm: {self.sync_confirm}"
            self.mp_logger.info(msg)

    def run(self) -> None:
        self.mp_logger = logger
        self.mp_logger.add("log_file.log", enqueue=True)
        self.debug()
        self.info()


class MpLoggerManager:
    _mp_lock = multiprocessing.Lock()
    _confirm_sync = uuid.uuid4()

    @staticmethod
    def get_logger():
        return MultiProcessLogger(MpLoggerManager._mp_lock, MpLoggerManager._confirm_sync)


if __name__ == '__main__':
    workers = []
    for x in range(10):
        worker = MpLoggerManager.get_logger()
        workers.append(worker)
        worker.start()
```

Output: 

```
2019-12-21 18:21:09.178 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-3 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.179 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-3 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.203 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-6 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.204 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-6 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.206 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-1 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.207 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-1 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.208 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-7 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.209 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-7 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.216 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-2 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.217 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-2 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.222 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-9 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.223 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-9 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.225 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-10 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.225 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-10 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.227 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-5 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.227 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-5 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.229 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-4 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.230 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-4 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.264 | DEBUG    | __mp_main__:debug:20 - Worker: MultiProcessLogger-8 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
2019-12-21 18:21:09.265 | INFO     | __mp_main__:info:26 - Worker: MultiProcessLogger-8 - Sync Confirm: c6201af3-a2b9-4aa6-bb60-f56667cd7650
```

**Comment by Delgan** [comment] 2019-12-22 09:40
> This is where my knowledge on multiprocessing and this library falls a bit short.

I did not know much about multiprocessing and Windows until I spent days refactoring the `logger` to fix #108. :smile: 

>  If loguru's `logger` is loaded after instantiation (ie. in `run()` ), is it the same object (in memory)? 

The object is definitely **not the same**. Even on Linux, spawning or forking a new process means the object is **deeply copied**. On Linux, this copy is handled by the OS so there's not much else to do. On Windows, however, your entire Python script will be re-loaded, so a new `logger` object will be created whenever you start a new worker. 

> I believe that one of the reasons it can't be passed during instantiation is because loguru's `logger` uses a `threading`-based queue for synchronization, which can't be pickled into a newly spawned process, right?

There are two ways to pass an object to another process: either by "inheriting" (during instantiation) or "copying" it (after instantiation). On Windows, in both case the object needs to be serialized using `pickle`. It's difficule to pass the `logger` to another process because of all not-picklable sinks it may contain (`sys.stderr` is not pickable, `open("file.log")` is not picklable, etc.). Even if you can copy it, the two sinks will be different objects and hence not synchronized.

Loguru uses a `multiprocessing`-based queue, the `Thread` only serves as a worker to write the enqueued log messages. This queue is not copy-able with `pickle`, but Python somehow manages to serialize it correctly if it is passed to the other process by inheritance. That's the whole trick. You need to pass the `logger` by inheritance, so the two sinks can be synchronized among several processes as their `Queue` will refer to the same object. If `enqueue=True`, Loguru takes care of removing all possibly not-picklabke attributes, so only the pickable `Queue` remains: https://github.com/Delgan/loguru/blob/256875af79b9773b4c8cf5a7ea4978c64ca14fa6/loguru/_handler.py#L317-L324




> But on the other hand, if I make my custom multi-processing logger wrapper this way and I synchronize the `logger`'s `sys.stderr` output within the worker (with a multiprocessing-lock or some other signal/lock) I imagine it would work.

Yeah, I guess sing a multiprocessing-lock should work should with `sys.stderr`. That might be a interesting code snippet to add to the documentation. I have not tested it, though. I'm curious to know how such implementation would handle file sinks for example.



> So I guess this is not a fool-proof solution but the docs gave me the idea it's simply not possible. That's why I thought writing a little example wrapper that at least gives the user _some_ options (including your caveat) might be interesting to include into that section of the docs.

I'm all for extending and improving the documentation, but I don't see me adding an alternative example is there is known flaws (conflicts due to two non-synchronized sinks) which does not exist using the first recommended implementation. That would look like a weaker / wrong solution, so why should I document it?

> I wrote a little example wrapper for what I'm talking about:

At that point, I think you don't need to add your sinks with `enqueue=True` because you have only one sink per process, so there is not synchronization needed. The conflicts are avoided by your `multiprocessing.Lock()`.

Do you think sub-classing `multiprocessing.Process` is needed? What about creating a custom sink and wrapping write with the lock?

```python
def mp_sink(msg):
    with lock:
        sys.stderr.write(msg)
```

**Comment by salihkilic** [comment] 2019-12-22 12:08
This is very strange, but I grabbed the Linux example from the docs to find out how I could work with your suggestions, but apparently now it works on windows? I'm using windows 10 btw.

```python
# Linux implementation
import multiprocessing
from loguru import logger


def my_process():
    logger.info("Executing function in child process")


if __name__ == "__main__":
    logger.add("file.log", enqueue=True)

    process = multiprocessing.Process(target=my_process)
    process.start()
    process.join()

    logger.info("Done")
```

```
C:\Users\my_username\PycharmProjects\project_name\venv\Scripts\python.exe C:/Users/my_username/PycharmProjects/project_name/test_pad10.py
2019-12-22 13:07:42.822 | INFO     | __mp_main__:my_process:7 - Executing function in child process
2019-12-22 13:07:42.832 | INFO     | __main__:<module>:17 - Done

Process finished with exit code 0
```

**Comment by salihkilic** [comment] 2019-12-22 14:31
Thanks for the reply @Delgan. I've been tinkering for a couple of hours now and it's a really annoying problem to solve on windows from within the library. I'll try making a custom sink as you suggested. Thanks for your time and input.

**Comment by Delgan** [comment] 2019-12-22 15:54
@salihkilic Can't you use the workaround suggested in the documentation? What bothers yuo with this solution?

**Comment by Delgan** [comment] 2020-04-03 09:52
I'm closing this issue for now. If you feel the documentation on `multiprocessing` needs improvements, please let me know. :+1:

**Closed by Delgan** 2020-04-03 09:52 UTC
Labels: docs, question
