### ISSUE TITLE
@logger.catch to log file?

### ISSUE THREAD

**Issue by ColinTheShark** [Delgan/loguru#188] opened 2019-12-08 20:38 UTC
I had a look through other issues and couldn't find anything relevant so here goes.

Can I intercept an unhandled exception in my function so that the printed traceback gets also put into my sink file? I tried with both `@logger.catch()` and `@logger.catch(reraise=True)`, both to no avail.

**Comment by Delgan** [comment] 2019-12-08 20:55
Exceptions occurring inside a function decorated with `@logger.catch` should be logged to your sinks.

Basically, `logger.catch()` is a s simple wrapper around your code which does the following:

```python
try:
    return some_function()
except Exception:
    logger.exception("An error occurred")
```

You may need to wrap your entire application of you want to catch any exception occurring anywhere, for example (`logger.catch()` can be used as a context manager too):

```python
if __name__ == "__main__":
    with logger.catch():
        start_my_app()
```
The stack trace should be written to your file as long as the exception is caught by Loguru, or that you manually log it using `logger.exception("Some message")` in the `except` block of exception handling.

**Comment by ColinTheShark** [comment] 2019-12-09 01:05
I've tried the context manager but the exception I get is still not thrown into my sink file...

```python3
logger.add(
    sink="./logs/app.log",
    enqueue=True,
    rotation="4 weeks",
    retention="4 months",
    encoding="utf-8",
    backtrace=True,
    diagnose=True,
)

if __name__ == "__main__":
    with logger.catch():
        my_app()
```
The exception does appear in my console though, which makes me wonder why it doesn't go into the log file 🤔

**Comment by Delgan** [comment] 2019-12-09 06:57
If you set:

```python
def my_app():
    1 / 0
```

You should see the exception reported in your file.

Does the exception you see in the console is colored and annotated with values? Do you use threads maybe? What is the type of the raised exception? By default, `logger.catch()` only catch `Exception` and not `BaseException`: [Exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)

**Comment by Delgan** [comment] 2020-01-11 10:51
@ColinTheShark Hi, did you solve this issue?

**Comment by ColinTheShark** [comment] 2020-01-11 16:30
No, I haven't found a solution that worked for me.

I have also not worked on the project where I encountered the issue. (It's a private project anyway, so what gives) :P

**Comment by Delgan** [comment] 2020-01-11 16:49
Ok, thanks for answering. I assume it's just a little configuration issue, but I wanted to make sure it wasn't a bug. :confused:

**Comment by Delgan** [comment] 2020-03-30 20:09
I'm closing this issue because I don't think it's a bug in Loguru. If you are able to reproduce the problem in a way that I can investigate it, don't hesitate to reopen it. :+1:

**Closed by Delgan** 2020-03-30 20:09 UTC
Labels: question

**Comment by mowarsadsa** [comment] 2022-03-03 01:09
similar problem 
from pyrogram import Client, filters
from loguru import logger

logger.debug("That's it, beautiful and simple logging!")
logger.add("out.log", backtrace=True, diagnose=True, format="{time} <level>{message}</level>", enqueue=True)

app = Client("t", config_file="bot/config.ini")
@app.on_message(filters.command('test', prefixes='!'))
def test(client, message):
	# this logs
    # logger.exception("What?!")
	# this doesnt
    raise Exception("Test")

 
def st():
	with logger.catch():
		app.run()
	
with logger.catch():
	st()

**Comment by Delgan** [comment] 2022-03-04 15:52
@mowarsadsa The `test` function does not seem decorated with `logger.catch()` so the raised `Exception` can't be captured by Loguru.
