### ISSUE TITLE
the thread id of logger is wrong

### ISSUE THREAD

**Issue by XiaobinZhao** [Delgan/loguru#936] opened 2023-08-08 01:42 UTC
1. run my app
```
(dc-A62zitQR-py3.7) root@xview:~/workspace/dc-api# python -m dc.main
INFO:     Started server process [2187117]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9099 (Press CTRL+C to quit)
```
2. got the pid is: 2187117
3. linux shell: `pstree -p 2187117`
```
(dc-A62zitQR-py3.7) root@xview:~/workspace/dc-api# pstree -p 2187117
python(2187117)─┬─{python}(2187121)
                ├─{python}(2187122)
                ├─{python}(2187123)
                ├─{python}(2187124)
                └─{python}(2187125)
```
4. when use loguru logger, got:
`2023-08-08 09:32:56,614:INFO    [139744829854080:2187057](main:<module>: 52) - Redis cache connect success !`
and the loguru format is 
`"{time:YYYY-MM-DD HH:mm:ss,SSS}:{level: <8}[{thread}:{process}] ({module}:{function}:{line: >3}) - {message}"`

5. why logger output the thread id is:  `139744829854080` but actual thread id is one of (2187121/2187122/2187123/2187124/2187125)

**Comment by Delgan** [comment] 2023-08-12 15:57
Hi @XiaobinZhao.

The "thread identifier" used by Loguru is derived from the [`ident`](https://docs.python.org/3/library/threading.html#threading.Thread.ident) attribute, which is different from the [`native_id`](https://docs.python.org/3/library/threading.html#threading.Thread.native_id) attribute you're observing when using `pstree`. The reason for this choice is simple: the `native_id` attribute did not exist when Loguru was created (it appeared in Python 3.8 while Loguru supports Python 3.5). However, I suppose using `.ident` nowadays is still preferable to `.native_id`, as it's guaranteed to be available regardless of the platform.

If you prefer the native identifier to be logged, you can patch the `logger` like that:

```python
def add_thread_native_id(record):
    record["extra"]["native_thread_id"] = threading.current_thread().native_id

logger.configure(patcher=add_thread_native_id)

logger.add(sys.stderr, format="[{extra[native_thread_id]}{process}] message")
```

**Comment by XiaobinZhao** [comment] 2023-09-06 03:43
@Delgan thanks very much~ but, i found somthing weaird~
1. i used native_id fllow your code
```
def add_thread_native_id(record):
    import threading
    record["extra"]["native_thread_id"] = threading.current_thread().native_id


log_format = "{time:YYYY-MM-DD HH:mm:ss,SSS}:{level: <8}[{extra[native_thread_id]}:{process}]" \
             "({module}:{function}:{line: >3}) - {message}"

logger.configure(patcher=add_thread_native_id)
```
2. then, after i run my fastapi app
```
root@xview:~/workspace/dc-api# python -m dc.main
INFO:     Started server process [143443]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9099 (Press CTRL+C to quit)
```
and, add logger in my any router api,i got
```
2023-09-06 11:36:03,461:INFO    [143443:143443](user:list_users: 77) - list_users
```
the pstree is:
```
root@xview:~/workspace/dc-api# pstree -p 143443
python(143443)─┬─{python}(143470)
               ├─{python}(143471)
               ├─{python}(143472)
               ├─{python}(143473)
               └─{python}(143474)
```
3. why cant i got the real thread id(143471/143472/143473/143474)? Is it the problem of fastapi ?

**Comment by Delgan** [comment] 2023-09-06 07:10
@XiaobinZhao I don't know It's working fine on my side while using FastAPI. I would need to see a fully reproducible example to help you further.

**Comment by XiaobinZhao** [comment] 2023-09-06 10:16
@Delgan 
finally,i find why my process have multi thread in the fastapi app,that is the `[uvloop](https://github.com/MagicStack/uvloop)`  module my project depency.My project depend uvloop==0.15.3, and when the version <0.15.3, example 0.15.2, there is only one thread. 
And the uvloop 0.15.3 code change is:
![image](https://github.com/Delgan/loguru/assets/6744069/4178a5a3-07fd-4ac2-9ae9-c9725810ad6a)

yeah ~ 

thanks @Delgan again~

**Comment by Delgan** [comment] 2023-09-06 10:38
Great, glad you figured it out. :+1: 

I'm closing this ticket then.

**Closed by Delgan** 2023-09-06 10:38 UTC
Labels: question
