### ISSUE TITLE
Unicode not working

### ISSUE THREAD

**Issue by Sir-Slimestone** [Delgan/loguru#330] opened 2020-09-19 22:33 UTC
The output is not displaying unicode properly, I end up with a bunch of giberish for error messages as a result.
![image](https://user-images.githubusercontent.com/47618065/93690452-c4613f00-fa95-11ea-93ed-f6fe8a5ff3de.png)

**Comment by Delgan** [comment] 2020-09-20 06:25
Hi @Sir-Slimestone.

It does not look like an unicode encoding problem, its looks more like an issue with colorization of the logs. The weird symbol you're seeing, like `▯[32m` are actually [ansi escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) used to add colors to the output. It seems your shell does not support these codes and hence they are not properly formatted. Actually, it seems `loguru` does not detect you're using Windows otherwise these codes should be converted using `colorama`.

May I ask you please:
* Which `loguru` version are you using?
* Do you call `logger.add(...)` or do you use the default handler?

In the meantime, you can explicitly disable colored output to make the gibberish disappear:

```python
logger.remove()
logger.add(sys.stderr, colorize=False)
```

**Comment by Delgan** [comment] 2021-03-15 21:17
Is this problem resolved @Sir-Slimestone?

**Comment by BenjiaH** [comment] 2021-03-24 12:02
Hi @Delgan!
I have a similar problem. The log file is "UTF-8" in this screenshot, and I have to change it into "ANSI" to make the Unicode working.
![image](https://user-images.githubusercontent.com/46958476/112307267-b3f77e80-8cdb-11eb-8ad6-99e1833e3d33.png)
I have tried your solution:
```python
sys.stderr, colorize=False
```
but it didn't work out.

**Comment by Delgan** [comment] 2021-03-24 19:16
Hi @BenjiaH.

This is actually not the same problem. :slightly_smiling_face: 
In your case, this seems indeed due to file encoding and is not related to `colorize` parameter.

This is not a bug in Loguru but in the way the file is written or read. You should specify `encoding="utf8"` while adding your handler. Maybe the default encoding is neither `"ascii"` nor `"utf8"` (it's platform dependent actually).

**Comment by BenjiaH** [comment] 2021-03-29 09:25
> Hi @BenjiaH.
> 
> This is actually not the same problem. 🙂
> In your case, this seems indeed due to file encoding and is not related to `colorize` parameter.
> 
> This is not a bug in Loguru but in the way the file is written or read. You should specify `encoding="utf8"` while adding your handler. Maybe the default encoding is neither `"ascii"` nor `"utf8"` (it's platform dependent actually).

thanks

**Comment by Delgan** [comment] 2022-04-23 10:17
Closing as it seems fixed. Feel free to re-open otherwise. :+1:

**Closed by Delgan** 2022-04-23 10:17 UTC
Labels: question
