### ISSUE TITLE
pytest capsys not caputuring output

### ISSUE THREAD

**Issue by rmminusrslash** [Delgan/loguru#703] opened 2022-09-09 08:53 UTC
Hey, 

according to the [docs](https://loguru.readthedocs.io/en/stable/api/logger.html) I was expecting the default logger to write to stderr:
> you can use the [Logger](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger) right after import as it comes pre-configured (logs are emitted to [sys.stderr](https://docs.python.org/3/library/sys.html#sys.stderr) by default)

So I was running this minimal example with pytest and was expecting it to work:

```
from loguru import logger


def test_logger(capsys):
    logger.error("Some Error")
    out, err = capsys.readouterr()
    assert "Some Error" in err

```

However it fails. When I add an explicit Handler that writed to stderr, it works. Why does the default handler not work?

**Comment by Delgan** [comment] 2022-09-18 19:44
Hi.

This is not working out of the box with `capsys` due to Pytest internals which replace `sys.stderr` with their own special object. Consequently, if `logger.add()` was called prior to the running the test, the Loguru's handler is lost.

**Comment by Delgan** [comment] 2022-10-09 09:31
I'm closing the issue as it seems resolved. Feel free to re-open otherwise.

**Closed by Delgan** 2022-10-09 09:31 UTC
Labels: question

**Comment by elisiariocouto** [comment] 2022-11-08 18:45
Hello @Delgan. I'm currently migrating my codebase to loguru and I found this issue. The funny thing is that pytest shows me the capture stderr, but the capsys fixture returns None. I tried to look for a workaround but only found one for caplog which is not my use-case.

**Comment by Delgan** [comment] 2022-11-08 21:13
@elisiariocouto Hi. Can you open a new issue with a fully reproducible example, please? It will makes it easier for me to grasp the problem.

**Comment by elisiariocouto** [comment] 2022-11-08 23:05
Sure, will do. Thanks
