### ISSUE TITLE
No newline when input

### ISSUE THREAD

**Issue by rewiaca** [Delgan/loguru#341] opened 2020-10-01 13:59 UTC
Code example:
```
while True:
    x = input("type:")
    try:
        do(x)   
    except:
        log.error("error")
```

STDout:

```
type: string
type: {log.error}
string
type: {log.error}
string
type: {log.error}
string
```

**Comment by Delgan** [comment] 2020-10-01 14:26
Hi @rewiaca, I'm not sure to understand your problem.

Can you please share a reproducible example?

Which `format` are you using while configuring the `logger`?

**Comment by rewiaca** [comment] 2020-10-01 15:07
> Hi @rewiaca, I'm not sure to understand your problem.
> 
> Can you please share a reproducible example?
> 
> Which `format` are you using while configuring the `logger`?

defaut one

try this:

from loguru import logger

input("type:")
logger.info("test")
input("type:")
logger.info("test")
input("type:")
logger.info("test")

**Comment by Delgan** [comment] 2020-10-01 15:23
Hum... It seems to work as expected on my computer:

![Screenshot at 17-22-41](https://user-images.githubusercontent.com/4193924/94829372-bb179100-040a-11eb-9d40-c47a740733c7.png)

Are you expecting another output?

**Comment by rewiaca** [comment] 2020-10-01 15:59
> Hum... It seems to work as expected on my computer:
> 
> ![Screenshot at 17-22-41](https://user-images.githubusercontent.com/4193924/94829372-bb179100-040a-11eb-9d40-c47a740733c7.png)
> 
> Are you expecting another output?

Tested. PyCharm only. Terminal the same as yours

**Comment by rewiaca** [comment] 2020-10-01 17:30
colorize=True , default log settings
```
type:test
type:2020-10-01 13:26:51.364 | INFO     | wlog:<module>:6 - test
test
type:2020-10-01 13:26:53.213 | INFO     | wlog:<module>:8 - test
test
2020-10-01 13:26:54.688 | INFO     | wlog:<module>:10 - test
​
Process finished with exit code 0
```
colorize=False , my own format style, could not figure out how to change settings for log with handler = 0

```
type:test
type:1 Oct 13:25:07.91 PM | INFO 	test 	wlog:6 <module>
test
type:1 Oct 13:25:09.75 PM | INFO 	test 	wlog:7 <module>
test
1 Oct 13:25:10.74 PM | INFO 	test 	wlog:10 <module>
​
Process finished with exit code 0
```
@Delgan print has correct display on same code

**Comment by Delgan** [comment] 2020-10-01 18:02
So, output seems malformed regardless of the `colorize` value. :confused: 

That's really weird. Sorry, I don't have many ideas to explain this behavior. Could that be related to one of your Pycharm plugins?  Is there any thread involved somewhere? You can use `enqueue=False` although it should be the default (this options writes logs using a thread and hence could explain the overlapped output).

**Comment by Delgan** [comment] 2021-03-15 21:47
I'm closing this issue because I honestly don't think the problem is due to Loguru. 

If you have other ideas to track down the problem, or can provide more information to further investigate this issue, feel free to reopen this ticket. :+1:

**Closed by Delgan** 2021-03-15 21:47 UTC
Labels: question
