### ISSUE TITLE
Log file name problem

### ISSUE THREAD

**Issue by geoff-kemmish** [Delgan/loguru#410] opened 2021-03-10 00:53 UTC
On Windows, using:

  logger.add("a/b.log")

( Yes, I know it's unlikely )

1) creates a file "b.log" in the current directory, and
2) creates the sub-directory "a", and then creates and writes to, the file "a/b.log"

I've tried to find where this is happening, but have failed so far.

Geoff

**Comment by Delgan** [comment] 2021-03-10 21:22
Hey @geoff-kemmish.

I tried `logger.add("a/b.log")` on Windows and it works as expected: it creates a single `"b.log"` file in the (newly created) `"b"` directory.

I'm pretty sure it's not possible for the `logger` to create the `b.log` in the current directory. Are you sure the file wasn't previously there? It's weird, but it's also possible that the `a` already existed and is actually a symlink to your current directory.

**Comment by Delgan** [comment] 2022-04-28 17:06
Closing as I'm unable to reproduce the issue. Fee free to re-open if you have more details.

**Closed by Delgan** 2022-04-28 17:06 UTC
Labels: question
