### ISSUE TITLE
Multiprocessing resource_tracker error when trying to use click completions while using enqueue

### ISSUE THREAD

**Issue by taranlu-houzz** [Delgan/loguru#477] opened 2021-07-23 22:05 UTC
# Issue:
I have found that if I add a sink that uses `enqueue=True`, using `click` completions as documented [here](https://click.palletsprojects.com/en/8.0.x/shell-completion/) causes an error (although the completion still works):
```
↴2 ~/----/loguru_click_completion_issue on  master [✘!?] is 📦 v1.0.0
❯ poetry shell
Spawning shell within /----/tool-AGIZ3qxU-py3.9
source /----/tool-AGIZ3qxU-py3.9/bin/activate.fish
Welcome to fish, the friendly interactive shell

↴3 ~/----/loguru_click_completion_issue on  master [✘!?] is 📦 v1.0.0
❯ source /----/tool-AGIZ3qxU-py3.9/bin/activate.fish

↴3 ~/----/loguru_click_completion_issue on  master [✘!?] is 📦 v1.0.0
❯ tool sub-/----/.asdf/installs/python/3.9.2/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdownA.)  sub-b  (Subcommand B.)
  warnings.warn('resource_tracker: There appear to be %d '

```

I have setup a basic project to illustrate the issue:
Project Structure:
```
loguru_click_completion_issue/
├── src
│   └── tool
│       ├── __init__.py
│       └── cli.py
├── poetry.lock
└── pyproject.toml
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "tool"
version = "1.0.0"
description = ""
authors = ["---- <---->"]
packages = [
    {include = "tool", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.7"

click = "^8.0.1"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
tool = "tool.cli:command"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

`src/tool/cli.py`:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-


"""Simple example of issue caused by click completion + loguru enqueued log."""


####################################################################################################
# Imports
####################################################################################################


# ==Standard Library==
import sys

# ==Site-Packages==
import click

from loguru import logger


####################################################################################################
# Logging
####################################################################################################


logger.add(sys.stderr, format="{time} {level} {message}", level="INFO", enqueue=True)


####################################################################################################
# Main
####################################################################################################


@click.command()
def sub_a() -> None:
    """Subcommand A."""

    print("A")


@click.command()
def sub_b() -> None:
    """Subcommand B."""

    print("B")


@click.group("tool")
def command() -> None:
    """Root command group."""

    pass


# ------------------------------------------------------------------------------------------------ #


# Assemble subcommands
command.add_command(sub_a)
command.add_command(sub_b)
```

`~/.config/fish/completions/tool.fish`:
```fish
function _tool_completion;
    set -l response;

    for value in (env _TOOL_COMPLETE=fish_complete COMP_WORDS=(commandline -cp) COMP_CWORD=(commandline -t) tool);
        set response $response $value;
    end;

    for completion in $response;
        set -l metadata (string split "," $completion);

        if test $metadata[1] = "dir";
            __fish_complete_directories $metadata[2];
        else if test $metadata[1] = "file";
            __fish_complete_path $metadata[2];
        else if test $metadata[1] = "plain";
            echo $metadata[2];
        end;
    end;
end;

complete --no-files --command tool --arguments "(_tool_completion)";

```

The issue does not occur on Python 3.7, but does happen on later versions. I initially raised [this](https://github.com/pallets/click/issues/2017) issue on the `click` bug tracker, but it closed since this is "not an issue with click," which I suppose is technically true.

----

# Environment:
- OS: macOS 10.15.7
- Python: > 3.7
- Shell: `fish`

**Comment by Delgan** [comment] 2021-07-24 07:13
Hi @taranlu-houzz. Can you please explain me where is `loguru` implied in the click completion utility? I don't see `logger.info()` used anywere? Is the mere fact of calling `logger.add()` with `enqueue=True` causing a bug?

**Comment by taranlu-houzz** [comment] 2021-07-25 05:44
Hi @Delgan, yes, just calling `logger.add()` with `enqueue=True` is all that is required to cause the error to occur in my test scenario.

**Comment by Delgan** [comment] 2021-07-25 09:08
Sorry @taranlu-houzz but I'm unable to reproduce the issue.

https://user-images.githubusercontent.com/4193924/126893268-1b97aed2-2833-4142-a272-326039f4fcfd.mp4

You can try to narrow down the problem by replacing `loguru` with the following code. It's a simplified version of what is going one when `enqueue=True` is used. Maybe this can help identify the source of the issue (`threading.Thread(daemon=True)`? `os.register_at_fork()`? `atexit.register()`?).

```python
import atexit
import multiprocessing
import os
import threading
import weakref

locks = weakref.WeakSet()

def acquire_locks():
    for lock in locks:
        lock.acquire()

def release_locks():
    for lock in locks:
        lock.release()

os.register_at_fork(
    before=acquire_locks,
    after_in_parent=release_locks,
    after_in_child=release_locks,
)

class LightLogger:
    def add(self):
        self._queue = multiprocessing.SimpleQueue()
        self._confirmation_event = multiprocessing.Event()
        self._confirmation_lock = multiprocessing.Lock()
        self._owner_process_pid = os.getpid()
        self._thread = threading.Thread(target=self._queued_writer, daemon=True)
        self._thread.start()
        self.lock = threading.Lock()
        locks.add(self.lock)

    def remove(self):
        with self.lock:
            if self._owner_process_pid != os.getpid():
                return
            self._queue.put(None)
            self._thread.join()

    def _queued_writer(self):
        message = None
        queue = self._queue

        lock = threading.Lock()
        locks.add(lock)

        while True:
            message = queue.get()

            if message is None:
                break

logger = LightLogger()
atexit.register(logger.remove)

logger.add()
```

**Comment by taranlu-houzz** [comment] 2021-07-26 17:50
Hmm... That is odd. I tried the code you posted above, and I still run into the same error. It seems like the only thing that might be different is the python installation... Out of curiosity, how is the version of Python used by `poetry` to build the virtualenv installed on your system? On mine, I am using `asdf`, so I am wondering if something is broken with the way it has installed Python. If it's not too much to ask, could you try installing Python 3.9.2 via `asdf` (assuming you are on macOS)?

**Comment by taranlu-houzz** [comment] 2021-07-26 17:54
This is a link to `asdf` documentation: http://asdf-vm.com/guide/getting-started.html#_1-install-dependencies

It should basically be something like this:
```
brew update
brew install asdf

echo -e "\nsource "(brew --prefix asdf)"/asdf.fish" >> ~/.config/fish/config.fish

asdf plugin add python
asdf install python 3.9.2
asdf global python 3.9.2
```

**Comment by taranlu-houzz** [comment] 2021-07-26 19:07
So, I also just had a co-worker test on another mac, and the same issue occurs. Interestingly, when I tried the same on Ubuntu 20.04 via WSL (Python 3.8.5), the issue did not appear. I wonder if this is a macOS problem...

**Comment by taranlu-houzz** [comment] 2021-07-26 19:19
This issue seems like it might be related: https://github.com/conda/conda/issues/9589
I don't use `conda` so can't comment on that, but it does match what I am seeing, and it appears that most of these users are on macOS.

**Comment by taranlu-houzz** [comment] 2021-07-26 19:33
This thread also seems like it might have useful information: https://githubmemory.com/repo/miurahr/aqtinstall/issues/264

**Comment by Delgan** [comment] 2021-07-26 19:47
I'm using Ubuntu 20.04, that's probably explain why I'm unable to reproduce the issue.

Maybe you can try to progressively remove parts of the snippet I previously shared, in order to identify which line is specifically causing the issue? It seems to happen due to `multiprocessing` according to the latest issue you linked.

**Comment by taranlu-houzz** [comment] 2021-07-26 20:19
Okay, I will try to take a look at that. Out of curiosity, do you know if `os.register_at_fork` also applies to processes created using the "spawn" method? That is apparently a major difference between Linux and macOS: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

The documentation seems to imply that it may since it says:
> Register callables to be executed when a new child process is forked using os.fork() or similar process cloning APIs.

I'm wondering if somehow the locks are either getting stuck or never being released.

**Comment by taranlu-houzz** [comment] 2021-07-26 21:49
Seems that the issue is caused by: `multiprocessing.SimpleQueue()`

I guess it does not clean itself up properly on macOS?

The below is all that is needed to trigger the error now:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-


"""Simple example of issue caused by click completion + loguru enqueued log."""


####################################################################################################
# Imports
####################################################################################################


# ==Standard Library==
import sys

# ==Site-Packages==
import click


####################################################################################################
# Logging
####################################################################################################


import multiprocessing


class LightLogger:
    def add(self):
        self._queue = multiprocessing.SimpleQueue()


logger = LightLogger()
logger.add()


####################################################################################################
# Main
####################################################################################################


@click.command()
def sub_a() -> None:
    """Subcommand A."""

    print("A")


@click.command()
def sub_b() -> None:
    """Subcommand B."""

    print("B")


@click.group("tool")
def command() -> None:
    """Root command group."""

    pass


# ------------------------------------------------------------------------------------------------ #


# Assemble subcommands
command.add_command(sub_a)
command.add_command(sub_b)
```

**Comment by taranlu-houzz** [comment] 2021-07-26 23:59
I also tried the "solution" suggested here: https://pythonspeed.com/articles/python-multiprocessing/

But adding:
```python
from multiprocessing import set_start_method
set_start_method("spawn")
```

Didn't seem to do anything...

**Comment by Delgan** [comment] 2021-07-27 18:37
Well done for pinpointing the problem!

It would be surprising if such a warning due to `SimpleQueue` had lasted so long without ever being noticed on macOS. Is there anything else special about your development environment or Python execution?

If you are able to upgrade to Python 3.9, they have added a [`SimpleQueue.close()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.SimpleQueue.close) method that may perhaps help you.

**Comment by taranlu-houzz** [comment] 2021-07-27 19:26
Unfortunately, I'm not able to move past 3.8 at the moment due to another dependency for the actual project.

As far as my environment goes, the only thing that is perhaps a little out of the ordinary is my use of `asdf` to manage my Python installations, but my co-worker was using the `brew` installed version of Python (3.9.6) and ran into the same issue.

It seems that there is something unique about the way that `click` completions are doing things, since just running the script directly does not produce the error.

**Comment by Delgan** [comment] 2021-07-27 19:36
Maybe it's worth asking for help on the `click` repository again now that you've managed to identify that `SimpleQueue` and macOS were both needed to reproduce the problem?

Also, I don't know if you noticed, but this issue seems related to yours: https://github.com/pallets/click/issues/1738 (no useful information unfortunately).

**Comment by taranlu-houzz** [comment] 2021-08-02 19:55
@Delgan So, just an update on this: the issue is caused by the `click.core._fast_exit()` function. Basically, on macOS (and presumably other platforms that do not support `fork`) the resources are not cleaned up properly in newer versions of Python. I have a PR (pallets/click#2023) that fixes the issue, so hopefully I will hear back on that soon.

**Comment by Delgan** [comment] 2021-08-05 17:21
Hey @taranlu-houzz, thanks for the update! I was following the corresponding ticket you opened on `click` repo. It has just been merged, well done for tracking the problem down! I'm closing this ticket consequently. :+1:

**Closed by Delgan** 2021-08-05 17:21 UTC
Labels: question
