### ISSUE TITLE
How to create logger with specific name?

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#204] opened 2020-01-17 16:42 UTC
I want to create a particular logger for logging events. How to do it?

**Comment by Delgan** [comment] 2020-01-17 16:50
Loguru only uses one global "anonymous" `logger` object. You just `import` it and use it from anywhere in your program.

It still possible to [`bind()`]() a name to identify log messages coming from a precise `logger`:

```python
from loguru import logger

def sink(message):
    record = message.record
    if record.get("name") == "your_named_logger":
        print("Log comes from your named logger")

logger = logger.bind(name="your_named_logger")

logger.info("A logger message")
```

**Comment by heckad** [comment] 2020-01-17 16:54
Thanks for the quick response.

If to write this 
```
import logging

from loguru import logger


class PropagateHandler(logging.Handler):
    def emit(self, record):
        logging.getLogger(record.name).handle(record)


logger.add(PropagateHandler(), format="{message}")

log = logger.bind(name='event log')
log.info("Hi")
```
then will be error ```KeyError: "Attempt to overwrite 'name' in LogRecord"``` What's wrong with this code?

**Comment by heckad** [comment] 2020-01-17 17:02
Also, why `add` apply to all loggers?
For example 
```
from loguru import logger

logger.remove()


def sink(message):
    print(message, end='')


log = logger.bind(name="your_named_logger")
log.add(sink)
log.info("Simple first message")

logger.info('Simple second message')
```
Why print twice?

**Comment by Delgan** [comment] 2020-01-17 17:11
> then will be error `KeyError: "Attempt to overwrite 'name' in LogRecord"` What's wrong with this code?

This happens when Loguru is used with a `Handler` from the standard `logging` library, as the `PropagateHandler()` in your case. Some keywords are forbidden by Python, see here: [`logging/__init__.py#L1548-L1552`](https://github.com/python/cpython/blob/c6b20be85c0de6f2355c67ae6e7e578941275cc0/Lib/logging/__init__.py#L1548-L1552).

If you plan to use `loguru` and `logging` at the same time, you should avoid using `.bind(name="...")` but rather use `.bind(logger_name="...")` for example. :/ 

> Also, why `add` apply to all loggers?

It doesn't, all loggers share the same set of handlers. It should not be printed twice. Actually, when I tried your code on my computer, it was not printed twice, so there is probably a typo somewhere else in your code.

**Comment by heckad** [comment] 2020-01-17 17:21
> It doesn't, all loggers share the same set of handlers. It should not be printed twice. Actually, when I tried your code on my computer, it was not printed twice, so there is probably a typo somewhere else in your code.

Very interesting.

![Снимок](https://user-images.githubusercontent.com/45011689/72632186-d028be80-3966-11ea-8708-146c56ccf131.PNG)

I use python 3.8.1

**Comment by Delgan** [comment] 2020-01-17 17:32
@heckad Oh, ok sorry, so this is the expected behavior then. I thought you was saying the **same** message was printed twice (which would have resulted in four messages overall).

So, as I said, all loggers share the same set of handlers. So, when you call `.info()` on any `logger` object, it will propagate the message to all registered handlers, no matter where `.add()` was called. Doing so eases the process of logging, as you don't have to repeatedly create new `logger` objects neither do you have to manage to which `logger` are attached the handlers.

You can use `logger` anywhere in your code and be sure that the message will be propagated to all configured handlers. You can customize the handling of such message in your sinks. That's the snippet I first shared. If you want to discard messages from one particular module, you can use a custom `filter` function based on the bound `name`.

If you really need to use two different `logger` objects with independent handlers, you can also use `copy.deepcopy()`, see [the documentation](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).

**Comment by heckad** [comment] 2020-01-17 17:34
> If you plan to use `loguru` and `logging` at the same time, you should avoid using `.bind(name="...")` but rather use `.bind(logger_name="...")` for example. :/

Maybe add a check on exist in name in `extra` in _log function on 1749 line and if no name then execute previous flow? What do you think?

**Comment by Delgan** [comment] 2020-01-17 17:40
> > 
> 
> Maybe add a check on exist in name in `extra` in _log function on 1749 line and if no name then execute previous flow? What do you think?

Using `name` in the `extra` dict is perfectly valid in the context of Loguru, the limitation is caused by the standard `logging`. I don't want to propagate this restriction to Loguru, especially considering there is some others attributes which are "forbidden". 

Maybe I could add a check in the Loguru `StandardSink`: https://github.com/Delgan/loguru/blob/3b66fb5b2ff38909dbeb817cb50e24f27677db8e/loguru/_simple_sinks.py#L43-L60

However, this will add an extra runtime check each time a message is logged, I'm not sure it's worth it.

**Comment by heckad** [comment] 2020-01-17 17:56
Why not add the ability to customise logger name?

**Comment by Delgan** [comment] 2020-01-17 18:02
Because `logger` don't have names, `name` is just an attribute of the `record` dict (it represents the module `__name__`, which is equivalent to `logging.getLogger(__name__)` widely used). 

It's part of Loguru's design: you only have to take care of your handlers, the `logger` is just a "dumb" object used to dispatch log messages to your handlers.

**Comment by heckad** [comment] 2020-01-17 18:12
I use `logging.getLogger("event")` for getting event logger in every needed place. Similar ability in loguru will be grate!

**Comment by Delgan** [comment] 2020-01-17 18:21
That's the purpose of `logger.bind()`. :)

```python
logger.add(sys.stderr)
logger.add("events.log", filter=lambda rec: "event" in rec["extra"])

logger.info("Some message")  # Only logged to stderr
logger.bind(event=True).info("Some event")  # Logged to 'events.log' too
```

**Comment by Delgan** [comment] 2020-03-08 07:26
@heckad Are you ok with the provided workaround? I don't think I should modify API regarding logger names at that point.

**Comment by heckad** [comment] 2020-03-08 13:17
Yes, we create event_logger like `logger.bind(event=True)` and use it.

**Comment by Delgan** [comment] 2020-03-08 13:40
Fine, that's the standard way to use named logger with Loguru. I'm closing this issue, then. :+1:

**Closed by Delgan** 2020-03-08 13:40 UTC
Labels: question

**Comment by Delgan** [comment] 2022-08-24 06:26
@Bobronium I'm thinking about a way to simplify interfacing with standard `logging` but it's not trivial. Thanks for your input, though.
