### ISSUE TITLE
Auto turn off colour if any non-ANSI tags in message rather than failing

### ISSUE THREAD

**Issue by mcarans** [Delgan/loguru#835] opened 2023-03-27 04:28 UTC
Is it possible for Loguru to have an option to autoescape non-ANSI tags or just print unescaped tags it doesn't understand like `<locals>` rather than failing with a message like `ValueError: Tag "<locals>" does not corespond to any known ansi directive, make sure you did not misspelled it`? 

This is related to [this closed issue](https://github.com/Delgan/loguru/issues/140) and occurs when using the InterceptHandler.

Looking at the code, I guess it would involve changing this bit: https://github.com/Delgan/loguru/blob/e0ca15b306ae86e1c64f5feff76dca2b4f165eed/loguru/_colorizer.py#L251-L256

It would become something like the following (borrowing from how \\ is treated):
```python
                if ansi is None:
                    self._tokens.append((TokenType.TEXT, markup))
                    continue
```

**Comment by Delgan** [comment] 2023-03-28 20:42
Hi.

Do you have some kind of reproducible example?

I don't see how it happens that Loguru tries to parse colors from a message intercepted with `InterceptHandler` (except if `opt(colors=True)` was added).

**Comment by mcarans** [comment] 2023-03-28 20:52
@Delgan Yes I am using `colors=True` because I want colours to be used where available. I have a standard `setup_logging()` function in a library that sets up loguru for all my other projects. Within that call, `InterceptHandler` is set up as follows:
```
    class InterceptHandler(logging.Handler):
        def emit(self, record):
            # Get corresponding Loguru level if it exists.
            try:
                level = logger.level(record.levelname).name
            except ValueError:
                level = record.levelno

            # Find caller from where originated the logged message.
            frame, depth = sys._getframe(6), 6
            while frame and frame.f_code.co_filename == logging.__file__:
                frame = frame.f_back
                depth += 1

            msg = record.getMessage().replace("<locals>", "\\<locals>")
            logger.opt(
                colors=True, depth=depth, exception=record.exc_info
            ).log(level, msg)
```

For now I have added `.replace("<locals>", "\\<locals>")` to deal with locals in the `InterceptHandler`, but other things within <> might be in output logs from my projects or dependent libraries, so I don't think this is a robust solution.

I like the idea of being able to configure loguru to print things within <> that don't correspond to ANSI colour tags without needing to escape them.

**Comment by Delgan** [comment] 2023-03-28 22:06
Thanks for the example of use case. :+1: 

However, I don't think it makes sense from Loguru side to add such option. The `InterceptHandler` is just not meant to be combined with `opt(colors=True)`. There is to many room for conflicts and uncertainties. If standard `logging` library is used, it should not rely on Loguru color markups.

Instead, I would suggest to either:
* Replace `opt(colors=True)` with a custom non-strict parsing function (example using [`python-ansimarkup`](https://github.com/gvalkov/python-ansimarkup) library)
* Colorize the message while the message is logged (example using [`rich`](https://github.com/Textualize/rich) library)
* Implement a custom `logging.Formatter` in charge of parsing + colorizing the message

**Comment by mcarans** [comment] 2023-03-28 22:37
Do you think it would be feasible for my `setup_logging` function that is called by all my projects to somehow override `logging.getLogger(__name__)` to return a loguru logger object directly rather than going by way of the standard logging infrastructure and the `InterceptHandler`?

**Comment by mcarans** [comment] 2023-03-30 04:28
@Delgan I think the fallback from colour to no colour on finding non-ANSI tag(s) could happen here if I udnerstood the code correctly:

https://github.com/Delgan/loguru/blob/e0ca15b306ae86e1c64f5feff76dca2b4f165eed/loguru/_logger.py#L1983-L1993 

I think it would involve a `try except` around the colour part and then copying the non-coloured lines in the `except`

**Comment by Delgan** [comment] 2023-03-31 08:46
Sorry @mcarans but I don't think I'm willing to make the colorization less strict. This would not fix the underlying problem, which is that we shouldn't try to parse a message that can contain either color tags and unrelated tags. Maybe the message will contain HTML tag like `<b>` that Loguru will transform while it shouldn't. There will always be possible ambiguities, so this is not a problem to be solved by loosing the parsing, the choice of colors or not must be explicitly stated by the user.

**Comment by mcarans** [comment] 2023-03-31 18:40
@Delgan I don't see this is as making colourisation less strict since colourisation would only occur if all the tags are colour tags (as now). It just changes what happens if non-colour tags are found so that logging doesn't fail with an exception. Also I envisaged this being an option not the default so the user would have to make an explicit decision that they want to do this. Would this allay your concerns?

**Comment by Delgan** [comment] 2023-04-01 08:44
As I said, this remains ambiguous for Loguru while parsing the message.

Someone might want to color a message but make a typo, e.g. `logger.info("<blakc>Not colored</>")`. We don't want this to be silently ignored, we want to report to the user that the color tag is invalid. See https://github.com/Delgan/loguru/issues/57, actually.

Someone might want to log markup tags which are not related to Loguru color directives. In such case, the user don't want them to be converted, e.g. `logger.info("Generated HTML templated: <b>Titlte</b></br><p>Text</p>")`.

If `colors=True` were to be applied, even with the strategy of "don't color if tags are not recognized", it will not work in all cases. That's why I don't even consider making this an option. Because I don't think this is the right way to solve your initial problem.

I would suggest instead to gradually migrate your modules to Loguru if you want to use its coloring feature, or to use a plugin to color the messages using standard logging.

**Comment by mcarans** [comment] 2023-04-11 03:16
I have resolved this with the following fix in my `InterceptHandler`:

```python
    class InterceptHandler(logging.Handler):
        def emit(self, record):
            # Get corresponding Loguru level if it exists.
            try:
                level = logger.level(record.levelname).name
            except ValueError:
                level = record.levelno

            # Find caller from where originated the logged message.
            frame, depth = sys._getframe(6), 6
            while frame and frame.f_code.co_filename == logging.__file__:
                frame = frame.f_back
                depth += 1

            msg = record.getMessage()
            try:
                logger.opt(
                    colors=True, depth=depth, exception=record.exc_info
                ).log(level, msg)
            except ValueError:
                logger.opt(
                    colors=False, depth=depth, exception=record.exc_info
                ).log(level, msg)
```

**Comment by Delgan** [comment] 2023-04-11 17:00
Fine, glad you found a solution that satisfies you. I'm closing this ticket, then. :+1:

**Closed by Delgan** 2023-04-11 17:00 UTC
