### ISSUE TITLE
How to prevent long log message from automatically being wrapped?

### ISSUE THREAD

**Issue by taranlu-houzz** [Delgan/loguru#454] opened 2021-05-27 09:30 UTC
It seems that when `loguru` emits a message, the message is first wrapped based on the size of the terminal before being output, which means that wrapping "formatting" gets baked into the message. My use case is that I am trying to debug the logging from a tool that is run in a subprocess. My parsing works correctly (basically, I am looking for a specific pattern in the log output), but when I directly run the tool, if the terminal is too small, the logging get formatted which makes it look incorrect (the regex should fail if it were to operate on the formatted message due to being broken into multiple lines).

I am wondering if there is a way to prevent this behavior to avoid this slightly confusing situation.

**Comment by Delgan** [comment] 2021-05-27 18:03
Hi @taranlu-houzz.

Loguru isn't applying any wrapping. The size of the console is ignored, it just `print()` the `str` messages.
The problem you are observing comes from your terminal or another external tool.

**Comment by taranlu-houzz** [comment] 2021-05-27 18:12
Hmm, I could have sworn output from other tools seemed to be printed with long lines that were then wrapped automatically by the terminal (and would rewrap if the terminal is resized after the fact)... I will try to look into it more. I'm using `kitty` for my terminal emulator and am inside of a `tmux` session.

**Comment by Delgan** [comment] 2022-04-28 18:25
I close this ticket because I think that the issue is not due to Loguru. Feel free to update it with further information if you have any.

**Closed by Delgan** 2022-04-28 18:25 UTC
Labels: question
