### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by pie-r** [Delgan/loguru#186] opened 2019-12-04 07:33 UTC
Hi all, 
I'm trying to understand which is the problem in the following line: 

--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(microseconds=151157), 'exception': None, 'extra': {'common_to_all': 'default', 'some_value': 42}, 'file': 'postgres_wrapper.py', 'function': 'scrivi_questo', 'level': 'INFO', 'line': 65, 'message': 'SCRIVI QUESTO', 'module': 'postgres_wrapper', 'name': 'postgres_wrapper', 'process': '12014', 'thread': '140287974258432', 'time': datetime(2019, 12, 4, 8, 29, 49, 157895, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'CET'))}
Traceback (most recent call last):
  File "/home/pigio/.pyenv/versions/3.7.2/envs/virtual-env-for-test-3.7.2/lib/python3.7/site-packages/loguru/_handler.py", line 144, in emit
    self._writer(str_record)
  File "/home/pigio/.pyenv/versions/3.7.2/envs/virtual-env-for-test-3.7.2/lib/python3.7/site-packages/loguru/_logger.py", line 696, in writer
    write(m)
ValueError: I/O operation on closed file
--- End of logging error ---

Any suggestion? I don't fully understand the concept behind logger, handler and so on.

**Comment by pie-r** [comment] 2019-12-04 07:53
After upgrading from loguru-0.3.2 to 0.4.0 the error disappear and now the logs are not sent visible to stdout

**Comment by Delgan** [comment] 2019-12-04 08:32
Hi @pie-r.

Could you please show me your logging configuration? What type of handlers do you `add()`? Also, do you use `multiprocessing`? It seems for some reason `sys.stdout` is closed, hence the error.

**Comment by pie-r** [comment] 2019-12-04 09:19
Surely:
I' have this configuration:
`
class RobotLoggerManager(object):
    ## Set class version
    ROBOT_LIBRARY_VERSION = '1.0'
    ## Create clear method given that this class is global
    ROBOT_LIBRARY_SCOPE   = 'GLOBAL'
    def __init__(self, fn_caller=None):
        fmt = "<level>{level: <8}</> | {time:HH:mm:ss} | {module: <25} | {function: <25} | {line: <4} | {message}"
        logger.remove()
        logger.configure(
        handlers=[
            dict(sink=sys.stderr, colorize=True, backtrace=True, diagnose=True, format=fmt, level="DEBUG")
            #dict(sink="file.log", enqueue=True, serialize=True),
        ],
        levels=[dict(name="CTM_DBG", no=33, color="<blue>")],
        extra={"common_to_all": "default"},
        patch=lambda record: record["extra"].update(some_value=42)
        )
`

i'm setting the logger.configure inside an __init__ method of a class. After that I import loguru in other file using "from loguru import logger" and i think that the problem is related to this thing.

**Comment by Delgan** [comment] 2019-12-04 12:17
Thanks. Do you know if the error is caused by the `sys.stderr` or `"file.log"` sink?
Also, do you use `multiprocessing` in any way, to start functions in different processes, with a `Pool()` worker for example? This is what has mainly changed with v0.4.0 and could explain the different behaviors you are seeing between the two versions.

**Comment by pie-r** [comment] 2019-12-04 12:52
@Delgan file.log is under comment, there is the #.
no multiprocessing, but only the logger configured in the init method of a python class. After that i call loguru in another file, without import that class.
So file1:
Contains LoggerManager and the __ init __ method.
File 2:
I have only "from loguru import logger"
I have not understood how the logger configuration is passed between files at the moment (if it happens because i use the from loguru import logger or for some other reason)

**Comment by Delgan** [comment] 2019-12-04 13:45
> I have not understood how the logger configuration is passed between files at the moment (if it happens because i use the from loguru import logger or for some other reason)

The `logger` is the same instance across your modules. So, whenever you call `.add()` or `.configure()` in one module, this also affects the other modules, as the `logger` object is the same. If you use a `logger` while your `LoggerManager()` is not initialized, it will just print to the default sink (which is `sys.stderr`). Maybe you should try to remove `enqueue=True` for now and see if it fixes the problem.

**Comment by pie-r** [comment] 2019-12-04 14:12
but how the logger object is passed across them? through the import?
This row is not used: #dict(sink="file.log", enqueue=True, serialize=True),
There is the # at the beginning.

**Comment by Delgan** [comment] 2019-12-04 15:51
> but how the logger object is passed across them? through the import?

Yes. When you `from loguru import logger`, your module get access to the Logger object and hence all the attached handlers. There is no need to explicitly pass it around, the `import` should suffice.



> This row is not used: #dict(sink="file.log", enqueue=True, serialize=True),
> There is the # at the beginning.

Yes, sorry. So, the problem comes from the `sys.stderr` sink. I think it's closed somewhere by some of your module or library. :confused: 

 It is difficult for me to investigate the problem without seeing code or a reproducible example.

**Comment by pie-r** [comment] 2019-12-04 16:16
I think that is closed by the __init__ method. Inside __init__ method everything work and i can use loguru without any problem.

Infact:
from loguru import logger
class LoggerManager(object):
    ## Set class version
    ROBOT_LIBRARY_VERSION = '1.0'
    ## Create clear method given that this class is global
    ROBOT_LIBRARY_SCOPE   = 'GLOBAL'
    def __init__(self, fn_caller=None):
        fmt = "<level>{level: <8}</> | {time:HH:mm:ss} | {module: <25} | {function: <25} | {line: <4} | {message}"
        logger.remove()
        logger.configure(
        handlers=[
            dict(sink=sys.stderr, colorize=True, backtrace=True, diagnose=True, format=fmt, level="DEBUG")
  
        ],
        levels=[dict(name="CTM_DBG", no=33, color="<blue>")],
        extra={"common_to_all": "default"},
        patch=lambda record: record["extra"].update(some_value=42)
        )

        logger.info("THIS IS OK")


Infact:
--------------------------------------------------------------------
CASE 1:
file1:
from loguru import logger

class LoggerManager(object):
    ## Set class version
    ROBOT_LIBRARY_VERSION = '1.0'
    ## Create clear method given that this class is global
    ROBOT_LIBRARY_SCOPE   = 'GLOBAL'
    def __init__(self, fn_caller=None):
         fmt = " xxxx "
        logger.remove()
        logger.configure(
        handlers=[
            dict(sink=sys.stderr, ......)
  
        ],
        )
        logger.info("THIS IS OK")

file2:
from loguru import logger
logger.info("THIS IS NOT OK")
--------------------------------------------------------------------
--------------------------------------------------------------------
CASE 2:
file1:
from loguru import logger
         fmt = " xxxx "
        logger.remove()
        logger.configure(
        handlers=[
            dict(sink=sys.stderr, ......)
  
        ],
        )
class LoggerManager(object):
    ## Set class version
    ROBOT_LIBRARY_VERSION = '1.0'
    ## Create clear method given that this class is global
    ROBOT_LIBRARY_SCOPE   = 'GLOBAL'
    def __init__(self, fn_caller=None):
        logger.info("THIS IS OK")

file2:
from loguru import logger
logger.info("THIS IS OK")
--------------------------------------------------------------------
CASE 3:
file1:
from loguru import logger

class LoggerManager(object):
    ## Set class version
    ROBOT_LIBRARY_VERSION = '1.0'
    ## Create clear method given that this class is global
    ROBOT_LIBRARY_SCOPE   = 'GLOBAL'
    def __init__(self, fn_caller=None):
        logger.info("THIS IS OK")

file2:
from loguru import logger
logger.info("THIS IS OK")

**Comment by Delgan** [comment] 2019-12-04 22:54
@pie-r Thanks for the code samples. Unfortunately, I'm still unable to reproduce the error.

How does `file1` and `file2` interfere with each others? How do you instantiate your `LoggerManage()`?
 
Loguru does not `close()` the `sys.stderr` stream. Never. I this might be a side-effect of another of your functions or libraries. I can only try to guess at this point.

**Comment by Delgan** [comment] 2020-03-30 20:06
I'm closing this issue because it looks like a configuration problem, not a bug.

If you need help to keep investigate this issue, please ask.

**Closed by Delgan** 2020-03-30 20:06 UTC
Labels: question
