### ISSUE TITLE
关于旋转文件压缩包

### ISSUE THREAD

**Issue by hutwuguangrong** [Delgan/loguru#512] opened 2021-09-24 07:55 UTC
您好，为什么会出现下面这个问题哈
![image](https://user-images.githubusercontent.com/60383030/134638796-de445b50-19a7-4efe-b27d-eb419aad26f4.png)
今天（2021-09-24）是正常的，但是前面几天压缩的 log 文件有多个

**Comment by hutwuguangrong** [comment] 2021-09-24 07:56
param = {
        'file_path': os.path.join(CURRENT_CONFIG.LOG_DIR, 'debug'),
        'level': "debug",
        'retention': CURRENT_CONFIG.LOG_RETENTION
    }
    rotation_handler_add(**param)


def rotation_handler_add(
    file_path: str,
    level: Optional[str] = "DEBUG",
    retention: Optional[int] = 10,
    compression: Optional[str] = "zip"
):
    rotation_file_path = "{0}_{{time:YYYY-MM-DD}}.log".format(file_path)
    msg_format = (
        "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | "
        "<blue>{process}</blue> | <level>{level: <8}</level> | "
        "<cyan>{name}:{file.path}</cyan>:<cyan>{function}</cyan>:"
        "<cyan>{line}</cyan> - "
        "<level>{message}</level>"
    )

    logger.add(
        rotation_file_path, level=level, format=msg_format, enqueue=True,
        rotation="00:00", retention=retention, compression=compression)

**Comment by Delgan** [comment] 2021-09-24 10:46
Hey @hutwuguangrong, are you sure you are not calling `rotation_handler_add()` multiple times?

It could happen that you're adding the same file handler twice, and everything looks fine (because sinks are writing to the same file) until rotation occurs (at that point, each handler try to compress the file independently).

Can I see your whole `logger` configuration maybe?

**Comment by hutwuguangrong** [comment] 2021-09-26 01:37
我是通过gunicorn启动的
![image](https://user-images.githubusercontent.com/60383030/134790201-f6e36e90-9aef-4133-a1f3-67f71d4c5009.png)
在flask的craeat_app函数里面有初始化logging
![image](https://user-images.githubusercontent.com/60383030/134790241-62423454-f001-4a79-b567-eeb467716c83.png)
![image](https://user-images.githubusercontent.com/60383030/134790247-049e2533-3317-44d5-b32d-1611d7bd3dc7.png)

**Comment by Delgan** [comment] 2021-10-02 17:50
Hey @hutwuguangrong.

I think the problem may come from calling `logger.add()` inside the [`post_fork()`](https://docs.gunicorn.org/en/0.17.2/configure.html#post-fork) function. The `post_fork()` function is called each time a worker is created. If you application needs to spawn multiple workers, this will add multiple sinks to Loguru, and each one will rotate on their own, creating the duplicated `.zip` you're seeing.

Could you call `rotation_handler_add()` inside your `init_logging()` instead?

Also, here is some documentation about Gunicorn and Loguru that you might find useful: [Unify Python logging for a Gunicorn/Uvicorn/FastAPI application](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/).

If you still can't find a solution, please can you share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can try to figure this out, please?

**Comment by Delgan** [comment] 2022-05-02 19:44
I'm closing this issue as I have no way to reproduce it.

**Closed by Delgan** 2022-05-02 19:44 UTC
Labels: question
